function:
  # Don't modify below here
  image: ${IMAGE_NAME}
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: 124e39c3-6dad-49ef-aede-d2cddac865c2
    SERVICE_CALLBACK_SUBSCRIPTION: pr-subscription-name
servicebus:
  resourceGroup: fees-pay-rg
  sbNamespace: "fees-pay-sb-preview"
  teamName: "Fees Pay"
  location: ukwest
  serviceplan: standard
  setup:
    topics:
    - name: servicecallbacktopic
      subscriptionNeeded: yes
  enabled: true
